name: Uploads operator

on:
  push:
    branches:
      - "main"

jobs:
  charmhub-upload:
    runs-on: ubuntu-20.04
    name: Charmhub upload charm
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Wait for integration tests to succeed
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: main
          check-name: "Integration tests"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - uses: canonical/charming-actions/upload-charm@2.0.0-rc
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "edge"
          upload-image: "false"

      - name: Chmod charmcraft logs
        if: steps.upload.conclusion == 'failure'
        run: |
          sudo chmod -R 777 /root/snap/charmcraft/common/cache/charmcraft/log/
      - name: Archive charmcraft logs
        if: steps.upload.conclusion == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: charmcraft-upload-logs
          path: /root/snap/charmcraft/common/cache/charmcraft/log/*.log
